//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public Author()
        {
            this.Posts = new HashSet<Post>();
        }
    
        public int aId { get; set; }
        public string aFirstName { get; set; }
        public string aLastName { get; set; }
        public string aUsername { get; set; }
        public string aPassword { get; set; }
        public Nullable<System.DateTime> aDateJoin { get; set; }
        public Nullable<byte> aIsWork { get; set; }
    
        public virtual ICollection<Post> Posts { get; set; }
    }
}
