//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int pid { get; set; }
        public string ptitle { get; set; }
        public string pexcerpt { get; set; }
        public string pcontent { get; set; }
        public Nullable<int> pauthor { get; set; }
        public Nullable<int> pimage { get; set; }
        public Nullable<int> ptags { get; set; }
        public Nullable<System.DateTime> pdate { get; set; }
        public Nullable<byte> pavailable { get; set; }
    }
}
