//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostMedia
    {
        public PostMedia()
        {
            this.Posts = new HashSet<Post>();
        }
    
        public int mid { get; set; }
        public string mname { get; set; }
        public string msource { get; set; }
        public Nullable<System.DateTime> mupload { get; set; }
        public Nullable<byte> mavailable { get; set; }
    
        public virtual ICollection<Post> Posts { get; set; }
    }
}
